# 配置文件

DAILY_TIME: "04:45" # 每日定时发送时间。该时间为系统时间，如果当前系统时间不为北京时间需要自行进行换算

START_DATE: "2021-10-24" # 纪念日
CITY: "大连"

BIRTHDAY:
  - "01-13"

APP_ID: "wxa69b371d41625276"
APP_SECRET: "f746d2af071a9fec43c433a4330fef39"

USER_ID: 
  - "oQ2kj6ZOcwx9GwGgAIlsTAQiaafY"
  - "oQ2kj6Uo7qE-XJSTpZX78lUAqPGw"
TEMPLATE_ID: "yd67S-S8fXY9zoQ6ih3yknLg2VxvqWuFQDEJ0o4bHzA"
